### ISSUE TITLE
Phoenix - deploying code (Joseph Miller)

### ISSUE THREAD

**Issue by madlep** [elixir-melbourne/meetup#15]
talk proposed by @joffotron

**Comment by joffotron** [comment]
Cool. I'm gonna have a think about what content might be useful for people, and to try and get my (newbie at Elixir) facts straight before spouting off ;)

**Comment by joffotron** [comment]
@madlep 

Having done more research into the options (and running into a few more gotchas with my own apps), I feel this topic might need a bit more coverage than a lightning style talk might warrant. 

Especially given that since it was suggested, https://github.com/bitwalker/distillery looks like it may be the successor to exrm, and I'll need some time to dig into the differences here.

I'll try and keep this issue updated with where I get to, but there's a decent chance it may not be ready for the October meetup.

**Comment by madlep** [comment]
Hey @joffotron 

That sounds fine. The original 10 min slot was just to fit in with the meeting last month. Feel free to talk for as long as needed.

Let me know how you're looking for October. If you want to move it back to November that's cool too.

**Comment by madlep** [comment]
Hey @joffotron. You keen to talk this Wednesday at the meetup, or leave it till next month?
